<?php

namespace app\controllers;


use yii\web\Controller;

class AppController extends Controller
{

    public function beforeAction($action)
    {
        //debug($action);
        $this->view->title = \Yii::$app->name;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}